import daisyui from 'daisyui';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica',
          'Arial',
          'Noto Sans',
          'Apple Color Emoji',
          'Segoe UI Emoji',
        ],
      },
    },
  },
  plugins: [daisyui],
  daisyui:{
    themes: [
      {
        "silk-dark": {
          "primary": "#9AA6FF",
          "primary-content": "#0B0F14",
          "secondary": "#9CE6D6",
          "secondary-content": "#071012",
          "accent": "#F2C6A0",
          "accent-content": "#120B07",
          "neutral": "#141A21",
          "neutral-content": "#D7DDE6",
          "base-100": "#0B0F14",
          "base-200": "#0F141B",
          "base-300": "#151C25",
          "base-content": "#D7DDE6",
          "info": "#6FB3FF",
          "info-content": "#06101C",
          "success": "#63E6A3",
          "success-content": "#06150D",
          "warning": "#FFD38A",
          "warning-content": "#1A1004",
          "error": "#FF7B7B",
          "error-content": "#1C0707",

          "--rounded-box": "1.25rem",
          "--rounded-btn": "0.9rem",
          "--rounded-badge": "0.9rem",
          "--animation-btn": "0.18s",
          "--animation-input": "0.18s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.9rem",
        },
      },
      {
        "silk": {
          "primary": "#5562FF",
          "primary-content": "#F8FAFF",
          "secondary": "#0EA5A5",
          "secondary-content": "#F3FFFD",
          "accent": "#C77D3C",
          "accent-content": "#FFF7F1",
          "neutral": "#1F2937",
          "neutral-content": "#F8FAFC",
          "base-100": "#FCFCFD",
          "base-200": "#F5F7FA",
          "base-300": "#EAEFF5",
          "base-content": "#0B1220",
          "info": "#2563EB",
          "info-content": "#EFF6FF",
          "success": "#16A34A",
          "success-content": "#F0FDF4",
          "warning": "#D97706",
          "warning-content": "#FFFBEB",
          "error": "#DC2626",
          "error-content": "#FEF2F2",

          "--rounded-box": "1.25rem",
          "--rounded-btn": "0.9rem",
          "--rounded-badge": "0.9rem",
          "--animation-btn": "0.18s",
          "--animation-input": "0.18s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.9rem",
        },
      },
    ],
    darkTheme: "silk-dark",
    base: true,
    styled: true,
    utils: true,
},
};